# black
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: # arguments to configure black
          - --line-length=88
          - --include='\.pyi?$'

          # these folders and files wont be formatted by black
          - --exclude="""\.git |
            _build|
            build|
            ignoreComment.txt|
            ignoreCommentandURL.txt|
            ignoreInvalid.txt|
            ignoreURL.txt|
            LICENSE|
            links.txt|
            quick.html|
            quick.txt|
            README.md|
            CONTRIBUTING.md|
            requirements.txt|
            dist"""

        language_version: python3.8

  # flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        args: # arguments to configure flake8
          # making isort line length compatible with black
          - "--max-line-length=120"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"

          # these are errors that will be ignored by flake8
          # check out their meaning here
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          - "--ignore=W605,W503,F401"
